input.onButtonPressed(Button.B, function () {
    PTKidsBITRobot.servoWrite(Servo_Write.P8, 110)
    basic.pause(1000)
    PTKidsBITRobot.servoWrite(Servo_Write.P12, 105)
    basic.pause(2500)
    PTKidsBITRobot.servoWrite(Servo_Write.P8, 15)
})
PTKidsBITRobot.setSensorColorAll(LED_Color.Blue)
PTKidsBITRobot.servoWrite(Servo_Write.P8, 15)
basic.pause(300)
PTKidsBITRobot.servoWrite(Servo_Write.P12, 170)
basic.showIcon(IconNames.Happy)
